apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ozuf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dvtz-tenant/rhtap-demo-app/hacbs-test-project-ozuf@sha256:2278420c79829a79b9eb227cae47d4250dd4aafe7ffcb820d7d9e42f11a44be3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
