apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ozuf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ozuf
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ozuf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ozuf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ozuf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dvtz-tenant/rhtap-demo-app/hacbs-test-project-ozuf@sha256:185cd79a0dfbf030e598ca24e978c66c98754104d21e1009e0d525a770f483ec
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
